### ISSUE TITLE
openai.LengthFinishReasonError

### ISSUE THREAD

**Issue by maximum2974** [wzf2000/MACRec#2]
**Description**:  
I encountered the following error while running the following command according to the README instructions:

```bash
python main.py --main Evaluate --data_file data/ml-100k/test.csv --system collaboration --system_config config/systems/collaboration/reflect_analyse_search.json --task sr
```

The error message is:
```bash
openai.LengthFinishReasonError: Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=300, prompt_tokens=513, total_tokens=813, completion_tokens_details=CompletionTokensDetails(audio_tokens=None, reasoning_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=None, cached_tokens=0))
```

Any guidance on how to resolve this error or adjust the configuration to avoid the length limit issue would be greatly appreciated.

**Comment by wzf2000** [comment]
You can adjust the `max_tokens` settings for each agent in the `config/agents/` directory. This will allow the model to generate longer responses.
