### ISSUE TITLE
There is no task related to Conversational Recommendation (cr) mentioned in the code

### ISSUE THREAD

**Issue by cngvng** [wzf2000/MACRec#3]
As in your article, I saw that you said that there would be a task related to CR in the article, however, when I checked your code, when I ran the task related to cr, I did not receive this task, did it exist, is the code you pushed incomplete, or is there any other confusion? I thank you.

**Comment by cngvng** [comment]
@wzf2000 can you explain for me?

**Comment by wzf2000** [comment]
I apologize for the delayed response to this issue, and thank you for your patience.

We have implemented demo functionality in the code where each task utilizes different agent combinations. Complete evaluation processes are currently only implemented for sequential recommendation and rating prediction tasks.

For conversational recommendation, we have set up a general conversational scenario with a recommendation intent. Therefore, if you wish to use this framework for traditional conversational recommendation research, additional task-specific implementations will be needed. However, if you'd like to try out the demo within our framework, you can use the `ChatTask` or our web demo code.
